name: Scheduled Ping

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch: 

jobs:
  pinger_job:
    name: A job to ping
    runs-on: ubuntu-latest
    steps:
      - id: ping
        uses: sisodiya2421/pinger@master
        env:
          URL: "https://hal.xstream-wtss.com"
          METHOD: "GET"
